[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "k8s.io/apiserver"

[[constraint]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.12.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
